### ISSUE TITLE
Bug: SharpHound v2.6.6 does not complete

### ISSUE THREAD

**Issue by hubert3** [SpecterOps/BloodHound#1528]
## Description:

Running SharpHound v2.6.6 on a large domain with the Default set of collection methods, every time the run gets up to approximately 380,000 objects it encounters one or more hosts where some collection method seems to take a very long time to complete or gets into a hung state. SharpHound console updates show the same number of objects for 15+ hours and the run never completes (have not tried letting it run for longer than this). 

Referencing legacy issue https://github.com/SpecterOps/BloodHound-Legacy/issues/541

### Are you intending to fix this bug?

no

## Component(s) Affected:

- Data Collector (SharpHound, AzureHound)

## Steps to Reproduce:

Run Sharphound with -c Default on my domain

## Expected Behavior:

SharpHound should apply a timeout (1-2 hours max?) to all collection methods so that runs will complete

## Actual Behavior:

SharpHound never completes and I can't ingest any data for the domain at all

## Screenshots/Code Snippets/Sample Files:

Old screenshot but it looks like this:

![Image](https://github.com/user-attachments/assets/2fa532c0-f21b-432b-b4f7-a3e22a823b7e)

## Environment Information:

SharpHound v2.6.6 running on a Windows 10 domain-joined machine

## Potential Solution (optional):

Add timeouts to all collection methods and to CertServices, LdapServices, WebClientService, SmbInfo as a priority, as one of these seems to be causing the hang in my environment

Set of collection methods that completes OK for me across several large domains:

Resolved Collection Methods: Group, LocalAdmin, GPOLocalGroup, Session, LoggedOn, Trusts, ACL, Container, RDP, ObjectProps, DCOM, SPNTargets, PSRemote

-c Default set of collection methods that hangs every time:

Resolved Collection Methods: Group, LocalAdmin, Session, Trusts, ACL, Container, RDP, ObjectProps, DCOM, SPNTargets, PSRemote, CertServices, LdapServices, WebClientService, SmbInfo

This would indicate it's one of the 4 methods above causing the issue

## Related Issues:

Legacy issue https://github.com/SpecterOps/BloodHound-Legacy/issues/541

## Contributor Checklist:

- [X] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [X] I have provided clear steps to reproduce the issue.
- [X] I have included relevant environment information details.

**Comment by hubert3** [comment]
I've narrowed it down further, it appears to be collection method **LdapServices** alone that is causing runs to hang in our environment. A run with all of the following methods completes OK:

Resolved Collection Methods: Group, LocalAdmin, GPOLocalGroup, Session, LoggedOn, Trusts, ACL, Container, RDP, ObjectProps, DCOM, SPNTargets, PSRemote, CertServices, WebClientService, SmbInfo

Just adding LdapServices as well causes the hang around the same number objects (370,000 to 380,000) every time.

**Comment by StephenHinck** [comment]
@hubert3 I've passed this on to our team. We're looking into it!

**Comment by StephenHinck** [comment]
@hubert3 we believe this was resolved with the release of v2.7.0 yesterday. Please let me know if you're still having issues.

**Comment by ChoiSG** [comment]
Hello folks, just chiming in - I used v2.7.0 but still encountered the same problem. AFAIR I didn't had this problem when using v2.6.1, so I'm not 100% sure if my problem is related to hubert3's problem. 

### Details

For me, the collection stops around 360,000~430,000 objects 

Specifically, SharpHound would collect 100% of the domain computers super fast. Then, it only collects around 1/10 of domain users and groups, then move on to CAs, containers, GPOs, etc. Then it finishes, or just hangs forever. 

For example, if there are 300,000 computers, 300,000 users, and 300,000 groups - SharpHound collects 300,000 computers, then collects around 30,000 users and 30,000 groups, then move on to CA, containers, GPOs. 

### Technical Details 

Test Environment: 
- SharpHound.exe in Windows 11, domain-joined computer 

Tools used for testing:
- SharpHound v2.7.0 downloaded from Release tab 
- SharpHound v2.7.0 compiled from the source code of the official repo 

Command used: 
```
./SharpHound.exe -c DCOnly 
./SharpHound.exe -c DCOnly [-d <domain>]
```

**Comment by hubert3** [comment]
@StephenHinck v2.7.1 completes with -c all now, but I think I'm seeing a similar issue to @ChoiSG where many domain users are now missing from the users json. 

There's lots of messages in the console about some actions taking longer than expected (sorry I don't have an exact log to hand).

Is it possible the new timeout code is aborting some collection actions too early? Is it possible to set timeout parameters apart from --portchecktimeout ?

**Comment by hubert3** [comment]
@ChoiSG are you still seeing the issue of incomplete user collection with 2.7.2 in your environment? I'm getting inconsistent results where some DCOnly runs seem to get all users but -c All does not
